project:
  type: website

website:
  title: "Ortsinformationen"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    lang: de
    lightbox: true
    
language:
  title-block-author-single: ""